### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by sachman** [kartikarora/udacity-reviewer-android#2]
The app doesn't install, giving the message 'App not installed'. I have tried in developer mode, while also enabled installing apps from external sources. I have MIUI 8.1 on my phone (MI) and Android version 6.0.1.

**Comment by kartikarora** [comment]
Hi @sachman 

It was an app signature issue. Fixed and tested, should now get installed properly. Please see the [latest release](https://github.com/kartikarora/urdashboard/releases/latest)

**Comment by sachman** [comment]
Hey @kartikarora 
Thanks for the help. It works fine now.
