### ISSUE TITLE
Crashes on clicking to copy the api access token

### ISSUE THREAD

**Issue by rajtheinnovator** [kartikarora/udacity-reviewer-android#3]
Click on profile --->>preferences ---->>Udacity Review API Token  --->>Copy to Clipboard

A video of the step at this link: https://drive.google.com/file/d/0B2kNov855nphOWdsVC14bk5BV0k/view?usp=sharing

https://media.giphy.com/media/l4EoTfVzngpoEijXW/giphy.gif

**Comment by kartikarora** [comment]
Thanks @rajtheinnovator I'll have a look

**Comment by kartikarora** [comment]
Could you share your device details please? @rajtheinnovator

**Comment by kartikarora** [comment]
@rajtheinnovator Nevermind, it will work correctly in the next RC.

**Comment by tshrjn** [comment]
This is still happening in the current RC.

**Comment by kartikarora** [comment]
@tshrjn Haven't released the next RC yet. But it will work if you build from source.

**Comment by kartikarora** [comment]
@tshrjn Fixed and [released](https://github.com/kartikarora/urdashboard/releases/latest)
