### ISSUE TITLE
Privacy Concerns?

### ISSUE THREAD

**Issue by tshrjn** [kartikarora/udacity-reviewer-android#5]
Really like the app, design and speed.
However, what all do you store in your database and who all have access to it?

**Comment by kartikarora** [comment]
Hi @tshrjn 

I'm in the process of completely removing Google Signin, so nothing will be stored in the cloud. Your Udacity JWT remains on the phone and is never sent anywhere.

**Comment by kartikarora** [comment]
@tshrjn Removed the Google Sign in. The token is only on your device now, nowhere else.
